// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA2L5FTHU4e4k4_fiCbplSIqsZAFOcswg',
    appId: '1:387564562162:web:f173e320952e4fa442926b',
    messagingSenderId: '387564562162',
    projectId: 'healu-20551',
    authDomain: 'healu-20551.firebaseapp.com',
    storageBucket: 'healu-20551.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXzS-2hLMjKwU8obRH1pd02dHrlSwre3I',
    appId: '1:387564562162:android:800d3082a1549f5742926b',
    messagingSenderId: '387564562162',
    projectId: 'healu-20551',
    storageBucket: 'healu-20551.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnY3xTKkz8aVAr2xDsvcsfwbzCWqsMEB4',
    appId: '1:387564562162:ios:5b2ce68f1fad509142926b',
    messagingSenderId: '387564562162',
    projectId: 'healu-20551',
    storageBucket: 'healu-20551.appspot.com',
    iosClientId: '387564562162-em9nmimriet9ae7nkabdk2hve1mmmfph.apps.googleusercontent.com',
    iosBundleId: 'com.example.healyou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnY3xTKkz8aVAr2xDsvcsfwbzCWqsMEB4',
    appId: '1:387564562162:ios:366bc6502f98de9942926b',
    messagingSenderId: '387564562162',
    projectId: 'healu-20551',
    storageBucket: 'healu-20551.appspot.com',
    iosClientId: '387564562162-v4k624kujsau9att9mengqd5rgnhqb3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.healyou.RunnerTests',
  );
}
